name: homesick
description: "A private letter-writing and time capsule app for meaningful connections."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3
  image_picker: ^1.1.2
  path_provider: ^2.1.5
  firebase_core: ^4.12.1
  firebase_auth: ^6.5.6
  google_sign_in: ^7.2.0
  cloud_firestore: ^6.7.1
  firebase_storage: ^13.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/branding/
    - assets/reference/
    - assets/images/backgrounds/
    - assets/images/logos/
    - assets/images/icons/
    - assets/images/decorations/
    - assets/images/flowers/

  fonts:
    - family: CormorantGaramond
      fonts:
        - asset: assets/fonts/CormorantGaramond-Regular.ttf
        - asset: assets/fonts/CormorantGaramond-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/CormorantGaramond-Bold.ttf
          weight: 700

    - family: Lora
      fonts:
        - asset: assets/fonts/Lora-Regular.ttf
        - asset: assets/fonts/Lora-Medium.ttf
          weight: 500
        - asset: assets/fonts/Lora-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Lora-Bold.ttf
          weight: 700

    - family: Caveat
      fonts:
        - asset: assets/fonts/Caveat-Regular.ttf
        - asset: assets/fonts/Caveat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Caveat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Caveat-Bold.ttf
          weight: 700

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/branding/app_icon.png"
  adaptive_icon_background: "#F7EFE7"
  adaptive_icon_foreground: "assets/branding/app_icon.png"